"""add scan activation and chat context fields

Revision ID: 9d4436eac4fe
Revises: 4e9c1b0d2a11
Create Date: 2026-09-23 13:22:29.791107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4436eac4fe'
down_revision: Union[str, Sequence[str], None] = '4e9c1b0d2a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_aws_scans_is_active'), 'aws_scans', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aws_scans_is_active'), table_name='aws_scans')
    # ### end Alembic commands ###
