"""phase 2 initial schema

Revision ID: d7815c1a9394
Revises: 
Create Date: 2026-09-18 12:11:13.388722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7815c1a9394'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('aws_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('account_arn', sa.String(length=512), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_aws_connection_user_account')
    )
    op.create_index(op.f('ix_aws_connections_account_id'), 'aws_connections', ['account_id'], unique=False)
    op.create_index(op.f('ix_aws_connections_user_id'), 'aws_connections', ['user_id'], unique=False)
    op.create_table('aws_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aws_connection_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('regions_json', sa.JSON(), nullable=False),
    sa.Column('zones_json', sa.JSON(), nullable=False),
    sa.Column('resources_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('timings_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['aws_connection_id'], ['aws_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aws_scans_aws_connection_id'), 'aws_scans', ['aws_connection_id'], unique=False)
    op.create_index(op.f('ix_aws_scans_scan_id'), 'aws_scans', ['scan_id'], unique=True)
    op.create_index(op.f('ix_aws_scans_user_id'), 'aws_scans', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aws_connection_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aws_connection_id'], ['aws_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_aws_connection_id'), 'chat_sessions', ['aws_connection_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_scan_id'), 'chat_sessions', ['scan_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent_json', sa.JSON(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_session_id'), 'chat_messages', ['chat_session_id'], unique=False)
    op.create_table('query_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=150), nullable=False),
    sa.Column('regions_json', sa.JSON(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('timings_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_executions_chat_session_id'), 'query_executions', ['chat_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_executions_chat_session_id'), table_name='query_executions')
    op.drop_table('query_executions')
    op.drop_index(op.f('ix_chat_messages_chat_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_scan_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_aws_connection_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_aws_scans_user_id'), table_name='aws_scans')
    op.drop_index(op.f('ix_aws_scans_scan_id'), table_name='aws_scans')
    op.drop_index(op.f('ix_aws_scans_aws_connection_id'), table_name='aws_scans')
    op.drop_table('aws_scans')
    op.drop_index(op.f('ix_aws_connections_user_id'), table_name='aws_connections')
    op.drop_index(op.f('ix_aws_connections_account_id'), table_name='aws_connections')
    op.drop_table('aws_connections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
